version: '2.1'
orbs:
  docker: circleci/docker@2.1.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - working_directory: tweet_service_app
      - docker/publish:
          context: twitter_clone_creds
          image: sancbansal/twitter_clone
          tag: eureka_server