version: '2.1'
orbs:
  docker: circleci/docker@2.1.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          path: ./twitter_service_app
          docker-context: twitter_service_app
          context: twitter_clone_creds
          image: sancbansal/twitter_clone
          tag: twitter_service_app