
version: "3.8"
services:
  tweet_db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tweet
    ports:
      - "3307:3306"
  tweet_service:
    image: tweet_service
    build: .
    ports:
      - "8080:8080"
    depends_on: ['tweet_db']
